---

roles:
  - name: haxwithaxe.keepalived
    src: https://github.com/haxwithaxe/ansible-keepalived
  - name: haxwithaxe.zfs_auto_snapshot
    src: https://github.com/haxwithaxe/ansible-zfs_auto_snapshot

collections:
  - name: community.general
  - name: devsec.hardening 
