---

# I encrypt the whole file in production.

root_password: "{{ 'super secret password for this host' | password_hash }}"

keepalived_host_vrrps_values:
  main:
    priority: 220
    interface: vmbr0

zfs_scrub_configs:
  - day_of_week: Monday
    pool: rpool

zfs_auto_snapshot_config:
  - name: rpool
    disabled: yes

