---

- name: Install required packages
  tags: bash,bash_completion,python
  apt:
    name:
      - git
      - screen
      - pipx
    update_cache: yes
    install_recommends: no
    state: latest

- name: Install required packages with recommends
  apt:
    name:
      - sudo
    state: latest

- name: Upgrade with pipx
  tags: python
  community.general.pipx:
    state: upgrade_all
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin

- name: Install required python packages
  tags: python
  community.general.pipx:
    name: "{{ item }}"
    state: install
  environment:
    PIPX_HOME: /opt/pipx
    PIPX_BIN_DIR: /usr/local/bin
  loop:
    - ntfyr

- name: Ensure ntfyr config dir exists
  tags: alert
  file:
    path: /etc/ntfyr
    state: directory
    mode: '0750'
    owner: root
    group: 44737

- name: Install ntfyr config
  tags: alert
  template:
    src: templates/ntfyr_config.ini.j2
    dest: /etc/ntfyr/config.ini
    mode: '0640'
    owner: root
    group: 44737
