---

- name: Client send LC_PVE_TICKET
  lineinfile:
    path: /etc/ssh/ssh_config
    regex: '^SendEnv( .*)( LC_PVE_TICKET)?( .*)$'
    line: 'SendEnv LC_PVE_TICKET'

- name: Set list of cluster peers
  set_fact:
    proxmox_cluster_peers: "{{ proxmox_cluster_peers | default([]) + [ hostvars[item].ansible_vmbr0.ipv4.address ] }}"
  loop: "{{ groups[proxmox_server_group] }}"

- name: Allow root login from proxmox cluster peers
  copy:
    dest: /etc/ssh/sshd_config.d/internal-cluster
    content: |
      Match Address {{ proxmox_cluster_peers | join(',') }}
          PermitRootLogin yes
          AcceptEnv LANG LC_PVE_TICKET LC_*
          SetEnv _CLUSTER_INTERNAL={{ ansible_machine_id }}
  notify:
    - RestartSSHD
